openapi: 3.0.1
info:
  title: Modern Treasury AccountCapability Connection API
  version: v1
  contact:
    name: Modern Treasury Engineering Team
    url: https://moderntreasury.com
  description: The Modern Treasury REST API. Please see https://docs.moderntreasury.com for more details.
servers:
- url: http://localhost:3000
- url: https://app.moderntreasury.com
tags:
- name: Connection
paths:
  /api/connections:
    get:
      summary: list connections
      tags:
      - Connection
      operationId: listConnections
      description: Get a list of all connections.
      security:
      - basic_auth: []
      parameters:
      - name: after_cursor
        in: query
        schema:
          type: string
          nullable: true
        required: false
      - name: per_page
        in: query
        required: false
        schema:
          type: integer
      - name: vendor_customer_id
        in: query
        schema:
          type: string
        required: false
        description: An identifier assigned by the vendor to your organization.
      - name: entity
        in: query
        schema:
          type: string
        required: false
        description: A string code representing the vendor (i.e. bank).
      responses:
        '200':
          description: successful
          headers:
            X-After-Cursor:
              schema:
                type: string
                nullable: true
              required: false
              description: The cursor for the next page. Including this in a call as `after_cursor` will return the next page.
            X-Per-Page:
              schema:
                type: integer
                nullable: true
              description: The current `per_page`.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/connection'
components:
  schemas:
    connection:
      type: object
      properties:
        id:
          type: string
          format: uuid
        object:
          type: string
        live_mode:
          type: boolean
          description: This field will be true if this object exists in the live environment or false if it exists in the test environment.
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        discarded_at:
          type: string
          format: date-time
          nullable: true
        vendor_id:
          type: string
          format: uuid
          description: Unique identifier for the bank or vendor.
        vendor_customer_id:
          type: string
          format: uuid
          description: An identifier given to this connection by the bank.
          nullable: true
        vendor_name:
          type: string
          description: A human-friendly name for the bank or vendor.
      additionalProperties: false
      minProperties: 9
      required:
      - id
      - object
      - live_mode
      - created_at
      - updated_at
      - discarded_at
      - vendor_id
      - vendor_customer_id
      - vendor_name
  securitySchemes:
    basic_auth:
      type: http
      scheme: basic
